#!/usr/bin/env python3
"""Generate and submit a single-GPU SLURM job that runs predict.py from a predict YAML.

The YAML's `slurm:` block holds the job's resources and environment (SLURM_DEFAULTS below);
every other key is a predict.py option (see predict.py / docs/PREDICTING.md). Overrides are
merged in, the resolved YAML is written to <output_dir>/predict_config.yaml, and the job runs
`predict.py <output_dir>/predict_config.yaml`, so the job is reproducible from its output dir.

Usage (from the repo root, on a login node):
  python3 tools/submit_predict.py <predict.yaml> [--set key=value ...] [--dry-run] [--debug] [--force]
"""
import argparse
import os
import shlex
import subprocess
import sys

from submit_experiments import REPO_ROOT, load_yaml, parse_value

SLURM_DEFAULTS = {
    "account": "gpu-emc-ai",
    "partition": "u1-h100",
    "qos": "gpu",
    "cpus_per_task": 8,
    "mem": "64G",
    "time": "02:00:00",
    "extra_sbatch": [],   # extra raw "#SBATCH ..." option strings
    "env_setup": [],      # shell lines run first (module load, conda activate, ...)
    "env_vars": {},       # exported into the job
    "python": "python",   # interpreter after env_setup
}
DEBUG_TIME = "00:30:00"

JOB_TEMPLATE = r"""#!/bin/bash -l
# Auto-generated by tools/submit_predict.py from @@SOURCE@@ (predict run "@@NAME@@").
# Don't edit by hand -- change the YAML and re-run the submitter (--dry-run to preview).
# @@DESCRIPTION@@
#
#SBATCH --account=@@ACCOUNT@@
@@QOS_LINE@@#SBATCH --partition=@@PARTITION@@
#SBATCH -J adaf_rtma_predict_@@NAME@@
#SBATCH -o @@OUT_DIR@@/log_%j.out
#SBATCH -e @@OUT_DIR@@/log_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=@@CPUS@@
#SBATCH --gres=gpu:1
#SBATCH --mem=@@MEM@@
#SBATCH -t @@TIME@@
#SBATCH --export=ALL
@@EXTRA_SBATCH@@
set -eo pipefail

cd "@@REPO_ROOT@@"
echo "Predict run: @@NAME@@ | Job: $SLURM_JOB_ID | Node: $SLURM_JOB_NODELIST | Started at $(date)"
startTime=$(date +%s)

# === Environment ===
@@ENV_SETUP@@
@@ENV_VARS@@
PYTHON="$(command -v @@PYTHON@@)"
echo "python: $PYTHON"
nvidia-smi -L || true

"$PYTHON" predict.py "@@CONFIG@@"

echo "runTime=$(( $(date +%s) - startTime ))s"
"""


def dump_yaml(data, path):
    try:
        from ruamel.yaml import YAML
        with open(path, "w") as f:
            YAML().dump(data, f)
    except ImportError:
        import yaml
        with open(path, "w") as f:
            yaml.safe_dump(data, f, sort_keys=False)


def set_dotted(cfg, dotted_key, value):
    keys = dotted_key.split(".")
    node = cfg
    for k in keys[:-1]:
        node = node.setdefault(k, {})
    node[keys[-1]] = value


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("config_file", help="predict YAML, e.g. configs/predict_example.yaml")
    parser.add_argument("--dry-run", action="store_true", help="write the job script, don't submit")
    parser.add_argument("--debug", action="store_true", help=f"override time limit to {DEBUG_TIME}")
    parser.add_argument("--force", action="store_true", help="allow overwriting existing metrics in output_dir")
    parser.add_argument("--set", action="append", default=[], metavar="KEY=VALUE",
                        help="override an option; dotted keys for nesting, e.g. slurm.time=01:00:00 (repeatable)")
    args = parser.parse_args()

    if not os.path.isfile(args.config_file):
        sys.exit(f"Config file not found: {args.config_file}")
    cfg = load_yaml(args.config_file)
    for kv in args.set:
        if "=" not in kv:
            sys.exit(f"--set expects KEY=VALUE, got {kv!r}")
        key, value = kv.split("=", 1)
        set_dotted(cfg, key.strip(), parse_value(value))

    slurm = {**SLURM_DEFAULTS, **(cfg.get("slurm") or {})}
    unknown = sorted(set(slurm) - set(SLURM_DEFAULTS))
    name = cfg.get("name") or os.path.splitext(os.path.basename(args.config_file))[0]
    cfg["name"] = name
    out_dir = str(cfg.get("output_dir", "predictions/{name}")).format(name=name)
    out_dir_abs = os.path.join(REPO_ROOT, out_dir)  # join keeps absolute paths as-is

    errors = []
    if unknown:
        errors.append(f"unknown slurm option(s) {unknown}; valid: {sorted(SLURM_DEFAULTS)}")
    for key in ("checkpoint", "config_filepath"):
        path = cfg.get(key)
        if key == "checkpoint" and not path:
            errors.append("checkpoint is required")
        elif path and not os.path.isfile(os.path.join(REPO_ROOT, path)):
            errors.append(f"{key} {path} does not exist")
    if not cfg.get("times") and not cfg.get("start_time"):
        errors.append("set start_time (and end_time), or times")
    if (os.path.isfile(os.path.join(out_dir_abs, "metrics_per_time.csv"))
            and not cfg.get("skip_existing") and not args.force):
        errors.append(f"{out_dir}/metrics_per_time.csv exists and would be overwritten -- "
                      "set skip_existing: true to resume, change name/output_dir, or pass --force")

    time_limit = DEBUG_TIME if args.debug else slurm["time"]
    config_copy = os.path.join(out_dir_abs, "predict_config.yaml")
    replacements = {
        "SOURCE": args.config_file,
        "NAME": name,
        "DESCRIPTION": str(cfg.get("description", "")).replace("\n", " "),
        "ACCOUNT": slurm["account"],
        "QOS_LINE": f"#SBATCH --qos={slurm['qos']}\n" if slurm["qos"] else "",
        "PARTITION": slurm["partition"],
        "OUT_DIR": out_dir_abs,
        "CPUS": slurm["cpus_per_task"],
        "MEM": slurm["mem"],
        "TIME": time_limit,
        "EXTRA_SBATCH": "\n".join(f"#SBATCH {o}" for o in slurm["extra_sbatch"]),
        "REPO_ROOT": REPO_ROOT,
        "ENV_SETUP": "\n".join(slurm["env_setup"]) or "# (no env_setup given)",
        "ENV_VARS": "\n".join(f"export {k}={shlex.quote(str(v))}" for k, v in slurm["env_vars"].items()),
        "PYTHON": slurm["python"],
        "CONFIG": config_copy,
    }
    script = JOB_TEMPLATE
    for key, value in replacements.items():
        script = script.replace(f"@@{key}@@", str(value))

    print(f"Predict run '{name}'" + (" [DRY RUN]" if args.dry_run else "") + (" [DEBUG]" if args.debug else ""))
    print(f"    checkpoint {cfg.get('checkpoint')}")
    print(f"    times {cfg.get('times') or (str(cfg.get('start_time')) + ' .. ' + str(cfg.get('end_time') or cfg.get('start_time')))}")
    print(f"    1 GPU, time {time_limit}, output_dir {out_dir_abs}")
    if errors:
        for e in errors:
            print(f"    ERROR: {e}")
        sys.exit(1)

    os.makedirs(out_dir_abs, exist_ok=True)  # sbatch needs the -o/-e dir to exist
    dump_yaml(cfg, config_copy)
    script_path = os.path.join(out_dir_abs, f"job_predict_{name}.sh")
    with open(script_path, "w", newline="\n") as f:
        f.write(script)
    os.chmod(script_path, 0o755)
    print(f"    config: {config_copy}")
    print(f"    job script: {script_path}")

    if args.dry_run:
        print(f"    [dry run] would run: sbatch {script_path}")
        return
    if subprocess.run(["which", "sbatch"], capture_output=True).returncode != 0:
        sys.exit("    ERROR: sbatch not found -- run on a login node, or use --dry-run")
    result = subprocess.run(["sbatch", script_path], cwd=REPO_ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"    ERROR: sbatch failed: {result.stderr.strip()}")
    print(f"    submitted: {result.stdout.strip()}")


if __name__ == "__main__":
    main()
