#!/usr/bin/env python3
"""Generate and submit single-GPU SLURM jobs that run predict.py from a YAML file.

The predict counterpart of tools/submit_experiments.py. See docs/PREDICTING.md.

A predict file is either
  * multi-run: `defaults:` + `predictions: {name: {overrides}}` (predict_configs.yaml), or
  * single-run: a flat mapping of options (configs/predict_example.yaml); its name is `name:`
    or the file's stem.
Each run is its defaults with its own keys on top; mappings (params, env_vars) are merged
key by key, so a run can add one `params` key without repeating the rest.

Every key is either a submit option (SUBMIT_DEFAULTS below: SLURM resources, environment)
or a predict.py option (PREDICT_DEFAULTS in predict.py). A `slurm:` block is also accepted
for submit options (the older single-run layout). The predict options are written to
<output_dir>/predict_config.yaml and the job runs `predict.py <that file>`, so every job is
reproducible from its output dir.

Usage (from the repo root, on a login node):
  python3 tools/submit_predict.py predict_configs.yaml [filter] [--dry-run] [--debug]
                                  [--version V] [--force] [--set key=value ...]
"""
import argparse
import ast
import copy
import difflib
import os
import re
import shlex
import subprocess
import sys

from submit_experiments import REPO_ROOT, config_keys, load_yaml, parse_value

# Consumed here; never written to the predict config.
SUBMIT_DEFAULTS = {
    # --- SLURM resources (always 1 node, 1 GPU) ---
    "account": "gpu-emc-ai",
    "partition": "u1-h100",
    "qos": "gpu",
    "cpus_per_task": 8,
    "mem": "64G",
    "time": "02:00:00",
    "extra_sbatch": [],   # extra raw "#SBATCH ..." option strings
    # --- environment ---
    "env_setup": [],      # shell lines run first (module load, conda activate, ...)
    "env_vars": {},       # exported into the job
    "python": "python",   # interpreter after env_setup
}
SUBMIT_KEYS = set(SUBMIT_DEFAULTS)
DEFAULT_CONFIG = "predict_configs.yaml"
DEFAULT_MODEL_CONFIG = "./config/params_lowres_ges_goes.yaml"  # predict.py's config_filepath default
DEBUG_TIME = "00:30:00"

JOB_TEMPLATE = r"""#!/bin/bash -l
# Auto-generated by tools/submit_predict.py from @@SOURCE@@ (predict run "@@NAME@@").
# Don't edit by hand -- change the YAML and re-run the submitter (--dry-run to preview).
# @@DESCRIPTION@@
#
#SBATCH --account=@@ACCOUNT@@
@@QOS_LINE@@#SBATCH --partition=@@PARTITION@@
#SBATCH -J adaf_rtma_predict_@@NAME@@
#SBATCH -o @@OUT_DIR@@/log_%j.out
#SBATCH -e @@OUT_DIR@@/log_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=@@CPUS@@
#SBATCH --gres=gpu:1
#SBATCH --mem=@@MEM@@
#SBATCH -t @@TIME@@
#SBATCH --export=ALL
@@EXTRA_SBATCH@@
set -eo pipefail

cd "@@REPO_ROOT@@"
echo "Predict run: @@NAME@@ | Job: $SLURM_JOB_ID | Node: $SLURM_JOB_NODELIST | Started at $(date)"
startTime=$(date +%s)

# === Environment ===
@@ENV_SETUP@@
@@ENV_VARS@@
PYTHON="$(command -v @@PYTHON@@)"
echo "python: $PYTHON"
nvidia-smi -L || true

"$PYTHON" predict.py "@@CONFIG@@"

echo "runTime=$(( $(date +%s) - startTime ))s"
"""

####################

def dump_yaml(data, path):
    try:
        from ruamel.yaml import YAML
        with open(path, "w") as f:
            YAML().dump(data, f)
    except ImportError:
        import yaml
        with open(path, "w") as f:
            yaml.safe_dump(data, f, sort_keys=False)


def set_dotted(cfg, dotted_key, value):
    keys = dotted_key.split(".")
    node = cfg
    for k in keys[:-1]:
        node = node.setdefault(k, {})
    node[keys[-1]] = value


def deep_merge(base, over):
    """base with over on top; nested mappings are merged key by key."""
    out = copy.deepcopy(base)
    for key, value in over.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = copy.deepcopy(value)
    return out


def predict_option_keys():
    """Keys of predict.py's PREDICT_DEFAULTS, read without importing predict.py (torch etc.)."""
    try:
        with open(os.path.join(REPO_ROOT, "predict.py")) as f:
            tree = ast.parse(f.read())
    except OSError as e:
        print(f"  warning: can't read predict.py to validate options ({e})", file=sys.stderr)
        return None
    for node in tree.body:
        if (isinstance(node, ast.Assign) and isinstance(node.value, ast.Dict)
                and any(isinstance(t, ast.Name) and t.id == "PREDICT_DEFAULTS" for t in node.targets)):
            return {k.value for k in node.value.keys}
    print("  warning: no PREDICT_DEFAULTS in predict.py; not validating options", file=sys.stderr)
    return None

####################

def resolve_runs(data, source, filter_str):
    if "predictions" in data:
        defaults = data.get("defaults") or {}
        runs = {name: deep_merge(defaults, overrides or {})
                for name, overrides in (data.get("predictions") or {}).items()}
    else:  # single-run file
        name = data.get("name") or os.path.splitext(os.path.basename(source))[0]
        runs = {name: dict(data)}

    for run in runs.values():  # older layout: submit options under slurm:
        run.update(run.pop("slurm", None) or {})
    if filter_str:
        runs = {k: v for k, v in runs.items() if filter_str in k}
    return runs


def build_job(name, run, args, predict_keys):
    run = copy.deepcopy(run)
    run.update(run.pop("slurm", None) or {})  # from a --set slurm.KEY=VALUE
    opts = {**SUBMIT_DEFAULTS, **{k: v for k, v in run.items() if k in SUBMIT_KEYS}}
    cfg = {k: v for k, v in run.items() if k not in SUBMIT_KEYS}
    cfg["name"] = name

    out_dir = str(cfg.get("output_dir") or "predictions/{name}").format(name=name)
    if args.version:
        out_dir = os.path.join(out_dir, args.version)
    cfg["output_dir"] = out_dir
    out_dir_abs = os.path.join(REPO_ROOT, out_dir)  # join keeps absolute paths as-is

    errors = []
    if predict_keys is not None:
        for key in cfg:
            if key not in predict_keys:
                hint = difflib.get_close_matches(key, sorted(predict_keys | SUBMIT_KEYS), n=1)
                errors.append(f"unknown option '{key}'" + (f" (did you mean '{hint[0]}'?)" if hint else "")
                              + " -- not a submit option or a predict.py option")
    model_config = cfg.get("config_filepath") or DEFAULT_MODEL_CONFIG
    if not os.path.isfile(os.path.join(REPO_ROOT, model_config)):
        errors.append(f"config_filepath {model_config} does not exist")
    else:
        known = config_keys(model_config)
        for key in (cfg.get("params") or {}) if known is not None else ():
            if key not in known:
                hint = difflib.get_close_matches(key, sorted(known), n=1)
                errors.append(f"unknown params key '{key}'" + (f" (did you mean '{hint[0]}'?)" if hint else "")
                              + f" -- not in {model_config}")
    if not cfg.get("checkpoint"):
        errors.append("checkpoint is required")
    elif not os.path.isfile(os.path.join(REPO_ROOT, cfg["checkpoint"])):
        errors.append(f"checkpoint {cfg['checkpoint']} does not exist")
    if not cfg.get("times") and not cfg.get("start_time"):
        errors.append("set start_time (and end_time), or times")
    if (os.path.isfile(os.path.join(out_dir_abs, "metrics_per_time.csv"))
            and not cfg.get("skip_existing") and not args.force):
        errors.append(f"{out_dir}/metrics_per_time.csv exists and would be overwritten -- "
                      "set skip_existing: true to resume, use --version, or pass --force")

    time = DEBUG_TIME if args.debug else opts["time"]
    config_copy = os.path.join(out_dir_abs, "predict_config.yaml")
    replacements = {
        "SOURCE": args.config_file,
        "NAME": name,
        "DESCRIPTION": str(cfg.get("description", "")).replace("\n", " "),
        "ACCOUNT": opts["account"],
        "QOS_LINE": f"#SBATCH --qos={opts['qos']}\n" if opts["qos"] else "",
        "PARTITION": opts["partition"],
        "OUT_DIR": out_dir_abs,
        "CPUS": opts["cpus_per_task"],
        "MEM": opts["mem"],
        "TIME": time,
        "EXTRA_SBATCH": "\n".join(f"#SBATCH {o}" for o in opts["extra_sbatch"]),
        "REPO_ROOT": REPO_ROOT,
        "ENV_SETUP": "\n".join(opts["env_setup"]) or "# (no env_setup given)",
        "ENV_VARS": "\n".join(f"export {k}={shlex.quote(str(v))}" for k, v in opts["env_vars"].items()),
        "PYTHON": opts["python"],
        "CONFIG": config_copy,
    }
    script = JOB_TEMPLATE
    for key, value in replacements.items():
        script = script.replace(f"@@{key}@@", str(value))
    leftover = re.findall(r"@@[A-Z_]+@@", script)
    assert not leftover, f"unfilled template placeholders {leftover}"

    return {"out_dir": out_dir_abs, "config_copy": config_copy, "cfg": cfg, "script": script,
            "errors": errors, "time": time}

####################

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("config_file", nargs="?", default=DEFAULT_CONFIG,
                        help=f"predict YAML ('-' = {DEFAULT_CONFIG})")
    parser.add_argument("filter", nargs="?", default="", help="only runs whose name contains this")
    parser.add_argument("--dry-run", action="store_true", help="write job scripts and configs, don't submit")
    parser.add_argument("--debug", action="store_true", help=f"override time limit to {DEBUG_TIME}")
    parser.add_argument("--version", default="", help="nest outputs under <output_dir>/<version>")
    parser.add_argument("--force", action="store_true", help="allow overwriting existing metrics in output_dir")
    parser.add_argument("--set", action="append", default=[], metavar="KEY=VALUE",
                        help="override an option for every selected run; dotted keys for nesting, "
                             "e.g. params.hold_out_obs_ratio=0.2 (repeatable)")
    args = parser.parse_args()

    if args.config_file == "-":
        args.config_file = DEFAULT_CONFIG
    if not os.path.isfile(args.config_file):
        sys.exit(f"Config file not found: {args.config_file}")

    overrides = []
    for kv in args.set:
        if "=" not in kv:
            sys.exit(f"--set expects KEY=VALUE, got {kv!r}")
        key, value = kv.split("=", 1)
        overrides.append((key.strip(), parse_value(value)))

    runs = resolve_runs(load_yaml(args.config_file), args.config_file, args.filter)
    if not runs:
        sys.exit(f"No predict runs in {args.config_file}" + (f" matching '{args.filter}'" if args.filter else ""))

    print(f"{len(runs)} predict run(s) from {args.config_file}"
          + (" [DRY RUN]" if args.dry_run else "") + (" [DEBUG]" if args.debug else ""))
    have_sbatch = subprocess.run(["which", "sbatch"], capture_output=True).returncode == 0 if not args.dry_run else True
    predict_keys = predict_option_keys()

    failures = 0
    for i, (name, run) in enumerate(runs.items(), 1):
        for key, value in overrides:
            set_dotted(run, key, value)
        job = build_job(name, run, args, predict_keys)
        cfg = job["cfg"]
        times = cfg.get("times") or f"{cfg.get('start_time')} .. {cfg.get('end_time') or cfg.get('start_time')}"
        print(f"\n[{i}] {name}" + (f" -- {cfg['description']}" if cfg.get("description") else ""))
        print(f"    checkpoint {cfg.get('checkpoint')}")
        print(f"    times {times}")
        print(f"    1 GPU, time {job['time']}, output_dir {job['out_dir']}")
        if job["errors"]:
            failures += 1
            for e in job["errors"]:
                print(f"    ERROR: {e}")
            continue

        os.makedirs(job["out_dir"], exist_ok=True)  # sbatch needs the -o/-e dir to exist
        dump_yaml(cfg, job["config_copy"])
        script_path = os.path.join(job["out_dir"], f"job_predict_{name}.sh")
        with open(script_path, "w", newline="\n") as f:
            f.write(job["script"])
        os.chmod(script_path, 0o755)
        print(f"    config: {job['config_copy']}")
        print(f"    job script: {script_path}")

        if args.dry_run:
            print(f"    [dry run] would run: sbatch {script_path}")
        elif not have_sbatch:
            failures += 1
            print("    ERROR: sbatch not found -- run on a login node, or use --dry-run")
        else:
            result = subprocess.run(["sbatch", script_path], cwd=REPO_ROOT, capture_output=True, text=True)
            if result.returncode == 0:
                print(f"    submitted: {result.stdout.strip()}")
            else:
                failures += 1
                print(f"    ERROR: sbatch failed: {result.stderr.strip()}")

    print(f"\n{len(runs) - failures}/{len(runs)} predict run(s) "
          + ("prepared" if args.dry_run else "submitted"))
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
